# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Ihm\choix_selection.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_ChoixSelection(object):
    def setupUi(self, ChoixSelection):
        ChoixSelection.setObjectName(_fromUtf8("ChoixSelection"))
        ChoixSelection.resize(499, 191)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(ChoixSelection)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtWidgets.QLabel(ChoixSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.repertoire = QtWidgets.QLineEdit(ChoixSelection)
        self.repertoire.setObjectName(_fromUtf8("repertoire"))
        self.horizontalLayout_4.addWidget(self.repertoire)
        self.bt_repertoire = QtWidgets.QPushButton(ChoixSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_repertoire.sizePolicy().hasHeightForWidth())
        self.bt_repertoire.setSizePolicy(sizePolicy)
        self.bt_repertoire.setMinimumSize(QtCore.QSize(40, 0))
        self.bt_repertoire.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bt_repertoire.setObjectName(_fromUtf8("bt_repertoire"))
        self.horizontalLayout_4.addWidget(self.bt_repertoire)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.bt_copie = QtWidgets.QRadioButton(ChoixSelection)
        self.bt_copie.setObjectName(_fromUtf8("bt_copie"))
        self.verticalLayout_5.addWidget(self.bt_copie)
        self.bt_compression = QtWidgets.QRadioButton(ChoixSelection)
        self.bt_compression.setObjectName(_fromUtf8("bt_compression"))
        self.verticalLayout_5.addWidget(self.bt_compression)
        self.reduction = QtWidgets.QHBoxLayout()
        self.reduction.setObjectName(_fromUtf8("reduction"))
        self.label_5 = QtWidgets.QLabel(ChoixSelection)
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.reduction.addWidget(self.label_5)
        self.sb_reduction = QtWidgets.QSpinBox(ChoixSelection)
        self.sb_reduction.setMinimum(1)
        self.sb_reduction.setMaximum(10)
        self.sb_reduction.setProperty("value", 2)
        self.sb_reduction.setObjectName(_fromUtf8("sb_reduction"))
        self.reduction.addWidget(self.sb_reduction)
        self.verticalLayout_5.addLayout(self.reduction)
        self.qualite = QtWidgets.QHBoxLayout()
        self.qualite.setObjectName(_fromUtf8("qualite"))
        self.label_4 = QtWidgets.QLabel(ChoixSelection)
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.qualite.addWidget(self.label_4)
        self.sb_qualite = QtWidgets.QSpinBox(ChoixSelection)
        self.sb_qualite.setMaximum(100)
        self.sb_qualite.setProperty("value", 90)
        self.sb_qualite.setObjectName(_fromUtf8("sb_qualite"))
        self.qualite.addWidget(self.sb_qualite)
        self.verticalLayout_5.addLayout(self.qualite)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.widget = QtWidgets.QWidget(ChoixSelection)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.rb_toutes = QtWidgets.QRadioButton(self.widget)
        self.rb_toutes.setChecked(True)
        self.rb_toutes.setObjectName(_fromUtf8("rb_toutes"))
        self.verticalLayout_2.addWidget(self.rb_toutes)
        self.rb_affichees = QtWidgets.QRadioButton(self.widget)
        self.rb_affichees.setObjectName(_fromUtf8("rb_affichees"))
        self.verticalLayout_2.addWidget(self.rb_affichees)
        self.rb_autres = QtWidgets.QRadioButton(self.widget)
        self.rb_autres.setObjectName(_fromUtf8("rb_autres"))
        self.verticalLayout_2.addWidget(self.rb_autres)
        self.bt_filtre = QtWidgets.QPushButton(self.widget)
        self.bt_filtre.setObjectName(_fromUtf8("bt_filtre"))
        self.verticalLayout_2.addWidget(self.bt_filtre)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.nb_photos = QtWidgets.QLabel(ChoixSelection)
        self.nb_photos.setObjectName(_fromUtf8("nb_photos"))
        self.verticalLayout_4.addWidget(self.nb_photos)
        self.taille_init = QtWidgets.QLabel(ChoixSelection)
        self.taille_init.setObjectName(_fromUtf8("taille_init"))
        self.verticalLayout_4.addWidget(self.taille_init)
        self.taille_finale = QtWidgets.QLabel(ChoixSelection)
        self.taille_finale.setObjectName(_fromUtf8("taille_finale"))
        self.verticalLayout_4.addWidget(self.taille_finale)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.okcancel = QtWidgets.QDialogButtonBox(ChoixSelection)
        self.okcancel.setOrientation(QtCore.Qt.Horizontal)
        self.okcancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.okcancel.setObjectName(_fromUtf8("okcancel"))
        self.verticalLayout.addWidget(self.okcancel)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(ChoixSelection)
        QtCore.QObject.connect(self.okcancel, QtCore.SIGNAL(_fromUtf8("accepted()")), ChoixSelection.accept)
        QtCore.QObject.connect(self.okcancel, QtCore.SIGNAL(_fromUtf8("rejected()")), ChoixSelection.reject)
        QtCore.QMetaObject.connectSlotsByName(ChoixSelection)

    def retranslateUi(self, ChoixSelection):
        ChoixSelection.setWindowTitle(_translate("ChoixSelection", "Génération de la selection", None))
        self.label.setText(_translate("ChoixSelection", "Répertoire", None))
        self.bt_repertoire.setText(_translate("ChoixSelection", "...", None))
        self.bt_copie.setText(_translate("ChoixSelection", "Copie", None))
        self.bt_compression.setText(_translate("ChoixSelection", "Compression", None))
        self.label_5.setText(_translate("ChoixSelection", "Reduction", None))
        self.label_4.setText(_translate("ChoixSelection", "Qualité", None))
        self.rb_toutes.setText(_translate("ChoixSelection", "Toutes", None))
        self.rb_affichees.setText(_translate("ChoixSelection", "Affichées", None))
        self.rb_autres.setText(_translate("ChoixSelection", "Autre", None))
        self.bt_filtre.setText(_translate("ChoixSelection", "Filtre ...", None))
        self.nb_photos.setText(_translate("ChoixSelection", "3 photos selectionnées", None))
        self.taille_init.setText(_translate("ChoixSelection", "3 Mo", None))
        self.taille_finale.setText(_translate("ChoixSelection", "TextLabel", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChoixSelection = QtWidgets.QDialog()
    ui = Ui_ChoixSelection()
    ui.setupUi(ChoixSelection)
    ChoixSelection.show()
    sys.exit(app.exec_())

