# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Ihm\choix_filtre2.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1150, 391)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.cb_repertoire = QtWidgets.QComboBox(self.centralwidget)
        self.cb_repertoire.setObjectName(_fromUtf8("cb_repertoire"))
        self.horizontalLayout_7.addWidget(self.cb_repertoire)
        self.bt_retirer_repertoire = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_retirer_repertoire.sizePolicy().hasHeightForWidth())
        self.bt_retirer_repertoire.setSizePolicy(sizePolicy)
        self.bt_retirer_repertoire.setMinimumSize(QtCore.QSize(30, 0))
        self.bt_retirer_repertoire.setMaximumSize(QtCore.QSize(30, 16777215))
        self.bt_retirer_repertoire.setText(_fromUtf8(""))
        icon = QtWidgets.QIcon()
        icon.addPixmap(QtWidgets.QPixmap(_fromUtf8("Delete-icon.png")), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.bt_retirer_repertoire.setIcon(icon)
        self.bt_retirer_repertoire.setObjectName(_fromUtf8("bt_retirer_repertoire"))
        self.horizontalLayout_7.addWidget(self.bt_retirer_repertoire)
        self.bt_repertoire = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_repertoire.sizePolicy().hasHeightForWidth())
        self.bt_repertoire.setSizePolicy(sizePolicy)
        self.bt_repertoire.setMinimumSize(QtCore.QSize(40, 0))
        self.bt_repertoire.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bt_repertoire.setObjectName(_fromUtf8("bt_repertoire"))
        self.horizontalLayout_7.addWidget(self.bt_repertoire)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.arborescence = QtWidgets.QTreeView(self.centralwidget)
        self.arborescence.setMinimumSize(QtCore.QSize(300, 0))
        self.arborescence.setObjectName(_fromUtf8("arborescence"))
        self.verticalLayout_8.addWidget(self.arborescence)
        self.fichier_progress = QtWidgets.QLabel(self.centralwidget)
        self.fichier_progress.setText(_fromUtf8(""))
        self.fichier_progress.setObjectName(_fromUtf8("fichier_progress"))
        self.verticalLayout_8.addWidget(self.fichier_progress)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_6.addWidget(self.progressBar)
        self.bt_annuler_progress = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_annuler_progress.sizePolicy().hasHeightForWidth())
        self.bt_annuler_progress.setSizePolicy(sizePolicy)
        self.bt_annuler_progress.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bt_annuler_progress.setObjectName(_fromUtf8("bt_annuler_progress"))
        self.horizontalLayout_6.addWidget(self.bt_annuler_progress)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.edtNomRepertoire = QtWidgets.QLineEdit(self.centralwidget)
        self.edtNomRepertoire.setObjectName(_fromUtf8("edtNomRepertoire"))
        self.verticalLayout_9.addWidget(self.edtNomRepertoire)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.btSupprimerRepertoire = QtWidgets.QPushButton(self.centralwidget)
        self.btSupprimerRepertoire.setObjectName(_fromUtf8("btSupprimerRepertoire"))
        self.horizontalLayout_10.addWidget(self.btSupprimerRepertoire)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.btCreerRepertoire = QtWidgets.QPushButton(self.centralwidget)
        self.btCreerRepertoire.setObjectName(_fromUtf8("btCreerRepertoire"))
        self.verticalLayout_10.addWidget(self.btCreerRepertoire)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.horizontalLayout_9.addLayout(self.verticalLayout_10)
        self.btDeplacerImages = QtWidgets.QPushButton(self.centralwidget)
        self.btDeplacerImages.setObjectName(_fromUtf8("btDeplacerImages"))
        self.horizontalLayout_9.addWidget(self.btDeplacerImages)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.cbox_selections = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_selections.sizePolicy().hasHeightForWidth())
        self.cbox_selections.setSizePolicy(sizePolicy)
        self.cbox_selections.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_selections.setObjectName(_fromUtf8("cbox_selections"))
        self.horizontalLayout_3.addWidget(self.cbox_selections)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.cb_toutes = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_toutes.setChecked(True)
        self.cb_toutes.setObjectName(_fromUtf8("cb_toutes"))
        self.verticalLayout_3.addWidget(self.cb_toutes)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.bt_ok = QtWidgets.QPushButton(self.centralwidget)
        self.bt_ok.setObjectName(_fromUtf8("bt_ok"))
        self.verticalLayout_3.addWidget(self.bt_ok)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gb_infos = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_infos.setCheckable(True)
        self.gb_infos.setChecked(False)
        self.gb_infos.setObjectName(_fromUtf8("gb_infos"))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gb_infos)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cb_0_etoile = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_0_etoile.setChecked(True)
        self.cb_0_etoile.setObjectName(_fromUtf8("cb_0_etoile"))
        self.horizontalLayout.addWidget(self.cb_0_etoile)
        self.cb_1_etoile = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_1_etoile.setChecked(True)
        self.cb_1_etoile.setObjectName(_fromUtf8("cb_1_etoile"))
        self.horizontalLayout.addWidget(self.cb_1_etoile)
        self.cb_2_etoiles = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_2_etoiles.setChecked(True)
        self.cb_2_etoiles.setObjectName(_fromUtf8("cb_2_etoiles"))
        self.horizontalLayout.addWidget(self.cb_2_etoiles)
        self.cb_3_etoiles = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_3_etoiles.setChecked(True)
        self.cb_3_etoiles.setObjectName(_fromUtf8("cb_3_etoiles"))
        self.horizontalLayout.addWidget(self.cb_3_etoiles)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.cb_traitee = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_traitee.setTristate(True)
        self.cb_traitee.setObjectName(_fromUtf8("cb_traitee"))
        self.verticalLayout_6.addWidget(self.cb_traitee)
        self.cb_panorama = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_panorama.setTristate(True)
        self.cb_panorama.setObjectName(_fromUtf8("cb_panorama"))
        self.verticalLayout_6.addWidget(self.cb_panorama)
        self.cb_retouche = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_retouche.setChecked(False)
        self.cb_retouche.setTristate(True)
        self.cb_retouche.setObjectName(_fromUtf8("cb_retouche"))
        self.verticalLayout_6.addWidget(self.cb_retouche)
        self.cb_nettete = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_nettete.setTristate(True)
        self.cb_nettete.setObjectName(_fromUtf8("cb_nettete"))
        self.verticalLayout_6.addWidget(self.cb_nettete)
        self.verticalLayout_4.addWidget(self.gb_infos)
        self.gb_nums = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_nums.setCheckable(True)
        self.gb_nums.setChecked(False)
        self.gb_nums.setObjectName(_fromUtf8("gb_nums"))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gb_nums)
        self.verticalLayout_5.setContentsMargins(5,5,5,5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtWidgets.QLabel(self.gb_nums)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.sb_min = QtWidgets.QSpinBox(self.gb_nums)
        self.sb_min.setMinimum(1)
        self.sb_min.setMaximum(9999)
        self.sb_min.setObjectName(_fromUtf8("sb_min"))
        self.horizontalLayout_4.addWidget(self.sb_min)
        self.label_2 = QtWidgets.QLabel(self.gb_nums)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.sb_max = QtWidgets.QSpinBox(self.gb_nums)
        self.sb_max.setMaximum(9999)
        self.sb_max.setObjectName(_fromUtf8("sb_max"))
        self.horizontalLayout_4.addWidget(self.sb_max)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.gb_nums)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.gb_dates = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_dates.setCheckable(True)
        self.gb_dates.setChecked(False)
        self.gb_dates.setObjectName(_fromUtf8("gb_dates"))
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.gb_dates)
        self.horizontalLayout_8.setContentsMargins(5,5,5,5)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.liste_dates = QtWidgets.QListWidget(self.gb_dates)
        self.liste_dates.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.liste_dates.setObjectName(_fromUtf8("liste_dates"))
        self.horizontalLayout_8.addWidget(self.liste_dates)
        self.horizontalLayout_5.addWidget(self.gb_dates)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.photo = QtWidgets.QLabel(self.frame)
        self.photo.setObjectName(_fromUtf8("photo"))
        self.verticalLayout_7.addWidget(self.photo)
        self.horizontalLayout_2.addWidget(self.frame)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuRep_photos = QtWidgets.QMenu(self.menubar)
        self.menuRep_photos.setObjectName(_fromUtf8("menuRep_photos"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionRecreerMiniatures = QtWidgets.QAction(MainWindow)
        self.actionRecreerMiniatures.setObjectName(_fromUtf8("actionRecreerMiniatures"))
        self.actionRecreerDates = QtWidgets.QAction(MainWindow)
        self.actionRecreerDates.setObjectName(_fromUtf8("actionRecreerDates"))
        self.actionDeplacerPhotos = QtWidgets.QAction(MainWindow)
        self.actionDeplacerPhotos.setObjectName(_fromUtf8("actionDeplacerPhotos"))
        self.actionDetruire = QtWidgets.QAction(MainWindow)
        self.actionDetruire.setObjectName(_fromUtf8("actionDetruire"))
        self.actionReinitialiser = QtWidgets.QAction(MainWindow)
        self.actionReinitialiser.setObjectName(_fromUtf8("actionReinitialiser"))
        self.menuRep_photos.addAction(self.actionRecreerMiniatures)
        self.menuRep_photos.addAction(self.actionRecreerDates)
        self.menuRep_photos.addAction(self.actionDeplacerPhotos)
        self.menuRep_photos.addAction(self.actionDetruire)
        self.menuRep_photos.addAction(self.actionReinitialiser)
        self.menubar.addAction(self.menuRep_photos.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_3.setText(_translate("MainWindow", "Répertoire", None))
        self.bt_repertoire.setText(_translate("MainWindow", "...", None))
        self.bt_annuler_progress.setText(_translate("MainWindow", "Stop", None))
        self.btSupprimerRepertoire.setText(_translate("MainWindow", "Supprimer", None))
        self.btCreerRepertoire.setText(_translate("MainWindow", "Créer", None))
        self.btDeplacerImages.setText(_translate("MainWindow", "Déplacer images\n"
" sélectionnées dans\n"
" le répertoire", None))
        self.label_4.setText(_translate("MainWindow", "Selection", None))
        self.cb_toutes.setText(_translate("MainWindow", "Toutes", None))
        self.bt_ok.setText(_translate("MainWindow", "Afficher", None))
        self.gb_infos.setTitle(_translate("MainWindow", "Infos", None))
        self.cb_0_etoile.setText(_translate("MainWindow", "0", None))
        self.cb_1_etoile.setText(_translate("MainWindow", "1", None))
        self.cb_2_etoiles.setText(_translate("MainWindow", "2", None))
        self.cb_3_etoiles.setText(_translate("MainWindow", "3", None))
        self.cb_traitee.setText(_translate("MainWindow", "Traitée", None))
        self.cb_panorama.setText(_translate("MainWindow", "Panorama", None))
        self.cb_retouche.setText(_translate("MainWindow", "Retouche", None))
        self.cb_nettete.setText(_translate("MainWindow", "Autre", None))
        self.gb_nums.setTitle(_translate("MainWindow", "Numéros photos", None))
        self.label.setText(_translate("MainWindow", "Photo", None))
        self.label_2.setText(_translate("MainWindow", "jusqu\'a", None))
        self.gb_dates.setTitle(_translate("MainWindow", "Date de prise de vue", None))
        self.photo.setText(_translate("MainWindow", "TextLabel", None))
        self.menuRep_photos.setTitle(_translate("MainWindow", "Rep photos", None))
        self.actionRecreerMiniatures.setText(_translate("MainWindow", "Recréer miniatures", None))
        self.actionRecreerDates.setText(_translate("MainWindow", "Recréer dates", None))
        self.actionDeplacerPhotos.setText(_translate("MainWindow", "Déplacer photos", None))
        self.actionDetruire.setText(_translate("MainWindow", "Détruire", None))
        self.actionReinitialiser.setText(_translate("MainWindow", "Réinitialiser", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

