# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ihm\choix_repertoire.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChoixRepertoire(object):
    def setupUi(self, ChoixRepertoire):
        ChoixRepertoire.setObjectName("ChoixRepertoire")
        ChoixRepertoire.resize(533, 114)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ChoixRepertoire)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ChoixRepertoire)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.repertoire = QtWidgets.QLineEdit(ChoixRepertoire)
        self.repertoire.setObjectName("repertoire")
        self.horizontalLayout.addWidget(self.repertoire)
        self.bt_repertoire = QtWidgets.QPushButton(ChoixRepertoire)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_repertoire.sizePolicy().hasHeightForWidth())
        self.bt_repertoire.setSizePolicy(sizePolicy)
        self.bt_repertoire.setMinimumSize(QtCore.QSize(40, 0))
        self.bt_repertoire.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bt_repertoire.setObjectName("bt_repertoire")
        self.horizontalLayout.addWidget(self.bt_repertoire)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.cb_arbo = QtWidgets.QCheckBox(ChoixRepertoire)
        self.cb_arbo.setObjectName("cb_arbo")
        self.verticalLayout_2.addWidget(self.cb_arbo)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.okcancel = QtWidgets.QDialogButtonBox(ChoixRepertoire)
        self.okcancel.setOrientation(QtCore.Qt.Horizontal)
        self.okcancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.okcancel.setObjectName("okcancel")
        self.verticalLayout_2.addWidget(self.okcancel)

        self.retranslateUi(ChoixRepertoire)
        self.okcancel.accepted.connect(ChoixRepertoire.accept) # type: ignore
        self.okcancel.rejected.connect(ChoixRepertoire.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ChoixRepertoire)

    def retranslateUi(self, ChoixRepertoire):
        _translate = QtCore.QCoreApplication.translate
        ChoixRepertoire.setWindowTitle(_translate("ChoixRepertoire", "Choix du repertoire des photos"))
        self.label.setText(_translate("ChoixRepertoire", "Répertoire"))
        self.bt_repertoire.setText(_translate("ChoixRepertoire", "..."))
        self.cb_arbo.setText(_translate("ChoixRepertoire", "arborescence"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChoixRepertoire = QtWidgets.QDialog()
    ui = Ui_ChoixRepertoire()
    ui.setupUi(ChoixRepertoire)
    ChoixRepertoire.show()
    sys.exit(app.exec_())
