# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Ihm\fen_arborescence.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Arborescence(object):
    def setupUi(self, Arborescence):
        Arborescence.setObjectName(_fromUtf8("Arborescence"))
        Arborescence.resize(990, 826)
        self.centralwidget = QtWidgets.QWidget(Arborescence)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.comboWorkspace = QtWidgets.QComboBox(self.centralwidget)
        self.comboWorkspace.setObjectName(_fromUtf8("comboWorkspace"))
        self.horizontalLayout_7.addWidget(self.comboWorkspace)
        self.btRetirerWorkspace = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btRetirerWorkspace.sizePolicy().hasHeightForWidth())
        self.btRetirerWorkspace.setSizePolicy(sizePolicy)
        self.btRetirerWorkspace.setMinimumSize(QtCore.QSize(30, 0))
        self.btRetirerWorkspace.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btRetirerWorkspace.setText(_fromUtf8(""))
        icon = QtWidgets.QIcon()
        icon.addPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/Delete-icon.png")), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.btRetirerWorkspace.setIcon(icon)
        self.btRetirerWorkspace.setObjectName(_fromUtf8("btRetirerWorkspace"))
        self.horizontalLayout_7.addWidget(self.btRetirerWorkspace)
        self.btAddWorkspace = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btAddWorkspace.sizePolicy().hasHeightForWidth())
        self.btAddWorkspace.setSizePolicy(sizePolicy)
        self.btAddWorkspace.setMinimumSize(QtCore.QSize(40, 0))
        self.btAddWorkspace.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btAddWorkspace.setObjectName(_fromUtf8("btAddWorkspace"))
        self.horizontalLayout_7.addWidget(self.btAddWorkspace)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayoutArbo = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayoutArbo.setObjectName(_fromUtf8("verticalLayoutArbo"))
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget_2)
        self.progressBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(240, 0))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_6.addWidget(self.progressBar)
        self.bt_annuler_progress = QtWidgets.QPushButton(self.layoutWidget_2)
        self.bt_annuler_progress.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_annuler_progress.sizePolicy().hasHeightForWidth())
        self.bt_annuler_progress.setSizePolicy(sizePolicy)
        self.bt_annuler_progress.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bt_annuler_progress.setObjectName(_fromUtf8("bt_annuler_progress"))
        self.horizontalLayout_6.addWidget(self.bt_annuler_progress)
        self.verticalLayoutArbo.addLayout(self.horizontalLayout_6)
        self.fichier_progress = QtWidgets.QLabel(self.layoutWidget_2)
        self.fichier_progress.setEnabled(True)
        self.fichier_progress.setText(_fromUtf8(""))
        self.fichier_progress.setObjectName(_fromUtf8("fichier_progress"))
        self.verticalLayoutArbo.addWidget(self.fichier_progress)
        self.btAfficher = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btAfficher.sizePolicy().hasHeightForWidth())
        self.btAfficher.setSizePolicy(sizePolicy)
        self.btAfficher.setMinimumSize(QtCore.QSize(300, 40))
        font = QtWidgets.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btAfficher.setFont(font)
        self.btAfficher.setObjectName(_fromUtf8("btAfficher"))
        self.verticalLayoutArbo.addWidget(self.btAfficher)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.btDeplacerImages = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btDeplacerImages.sizePolicy().hasHeightForWidth())
        self.btDeplacerImages.setSizePolicy(sizePolicy)
        self.btDeplacerImages.setMinimumSize(QtCore.QSize(150, 0))
        self.btDeplacerImages.setObjectName(_fromUtf8("btDeplacerImages"))
        self.horizontalLayout_24.addWidget(self.btDeplacerImages)
        self.btCopierImages = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btCopierImages.sizePolicy().hasHeightForWidth())
        self.btCopierImages.setSizePolicy(sizePolicy)
        self.btCopierImages.setMinimumSize(QtCore.QSize(150, 0))
        self.btCopierImages.setObjectName(_fromUtf8("btCopierImages"))
        self.horizontalLayout_24.addWidget(self.btCopierImages)
        self.verticalLayoutArbo.addLayout(self.horizontalLayout_24)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.photo = QtWidgets.QLabel(self.layoutWidget)
        self.photo.setObjectName(_fromUtf8("photo"))
        self.verticalLayout_3.addWidget(self.photo)
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 311, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.btSupprimerRepertoire = QtWidgets.QPushButton(self.groupBox)
        self.btSupprimerRepertoire.setObjectName(_fromUtf8("btSupprimerRepertoire"))
        self.gridLayout.addWidget(self.btSupprimerRepertoire, 0, 1, 1, 1)
        self.btDeplacerRepertoire = QtWidgets.QPushButton(self.groupBox)
        self.btDeplacerRepertoire.setObjectName(_fromUtf8("btDeplacerRepertoire"))
        self.gridLayout.addWidget(self.btDeplacerRepertoire, 1, 1, 1, 1)
        self.btCtrlXRepertoire = QtWidgets.QPushButton(self.groupBox)
        self.btCtrlXRepertoire.setMinimumSize(QtCore.QSize(80, 0))
        self.btCtrlXRepertoire.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btCtrlXRepertoire.setObjectName(_fromUtf8("btCtrlXRepertoire"))
        self.gridLayout.addWidget(self.btCtrlXRepertoire, 1, 0, 1, 1)
        self.lblRepADeplacer = QtWidgets.QLabel(self.groupBox)
        self.lblRepADeplacer.setText(_fromUtf8(""))
        self.lblRepADeplacer.setObjectName(_fromUtf8("lblRepADeplacer"))
        self.gridLayout.addWidget(self.lblRepADeplacer, 2, 1, 1, 1)
        self.btCreerRepertoire = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btCreerRepertoire.sizePolicy().hasHeightForWidth())
        self.btCreerRepertoire.setSizePolicy(sizePolicy)
        self.btCreerRepertoire.setObjectName(_fromUtf8("btCreerRepertoire"))
        self.gridLayout.addWidget(self.btCreerRepertoire, 0, 0, 1, 1)
        self.btViderRepertoire = QtWidgets.QPushButton(self.groupBox)
        self.btViderRepertoire.setObjectName(_fromUtf8("btViderRepertoire"))
        self.gridLayout.addWidget(self.btViderRepertoire, 0, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 311, 350))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.btRecreerMiniatures = QtWidgets.QPushButton(self.groupBox_2)
        self.btRecreerMiniatures.setMinimumSize(QtCore.QSize(120, 0))
        self.btRecreerMiniatures.setObjectName(_fromUtf8("btRecreerMiniatures"))
        self.horizontalLayout_16.addWidget(self.btRecreerMiniatures)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.btDetruireTriPhotos = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btDetruireTriPhotos.sizePolicy().hasHeightForWidth())
        self.btDetruireTriPhotos.setSizePolicy(sizePolicy)
        self.btDetruireTriPhotos.setMinimumSize(QtCore.QSize(120, 0))
        self.btDetruireTriPhotos.setMaximumSize(QtCore.QSize(400, 16777215))
        self.btDetruireTriPhotos.setObjectName(_fromUtf8("btDetruireTriPhotos"))
        self.horizontalLayout_17.addWidget(self.btDetruireTriPhotos)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.cb_album_termine = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_album_termine.setObjectName(_fromUtf8("cb_album_termine"))
        self.verticalLayout_8.addWidget(self.cb_album_termine)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.nb_pano = QtWidgets.QLabel(self.groupBox_2)
        self.nb_pano.setObjectName(_fromUtf8("nb_pano"))
        self.horizontalLayout_31.addWidget(self.nb_pano)
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_31.addWidget(self.label_26)
        self.nb_recup = QtWidgets.QLabel(self.groupBox_2)
        self.nb_recup.setObjectName(_fromUtf8("nb_recup"))
        self.horizontalLayout_31.addWidget(self.nb_recup)
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_31.addWidget(self.label_27)
        self.nb_retouche = QtWidgets.QLabel(self.groupBox_2)
        self.nb_retouche.setObjectName(_fromUtf8("nb_retouche"))
        self.horizontalLayout_31.addWidget(self.nb_retouche)
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_31.addWidget(self.label_28)
        self.verticalLayout_8.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.icon1 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon1.sizePolicy().hasHeightForWidth())
        self.icon1.setSizePolicy(sizePolicy)
        self.icon1.setMaximumSize(QtCore.QSize(25, 16777215))
        self.icon1.setText(_fromUtf8(""))
        self.icon1.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/icon/repNormal1.png")))
        self.icon1.setObjectName(_fromUtf8("icon1"))
        self.horizontalLayout_22.addWidget(self.icon1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setText(_fromUtf8(""))
        self.label_23.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/repko.png")))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_22.addWidget(self.label_23)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.icon2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon2.sizePolicy().hasHeightForWidth())
        self.icon2.setSizePolicy(sizePolicy)
        self.icon2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.icon2.setText(_fromUtf8(""))
        self.icon2.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/repImage.png")))
        self.icon2.setObjectName(_fromUtf8("icon2"))
        self.horizontalLayout_26.addWidget(self.icon2)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/repko.png")))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_26.addWidget(self.label_24)
        self.verticalLayout_8.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.icon3 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon3.sizePolicy().hasHeightForWidth())
        self.icon3.setSizePolicy(sizePolicy)
        self.icon3.setMaximumSize(QtCore.QSize(25, 16777215))
        self.icon3.setText(_fromUtf8(""))
        self.icon3.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/repVideo.png")))
        self.icon3.setObjectName(_fromUtf8("icon3"))
        self.horizontalLayout_23.addWidget(self.icon3)
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/repko.png")))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_23.addWidget(self.label_25)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.icon4 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon4.sizePolicy().hasHeightForWidth())
        self.icon4.setSizePolicy(sizePolicy)
        self.icon4.setMaximumSize(QtCore.QSize(25, 16777215))
        self.icon4.setText(_fromUtf8(""))
        self.icon4.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/repTri.png")))
        self.icon4.setObjectName(_fromUtf8("icon4"))
        self.horizontalLayout_25.addWidget(self.icon4)
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        self.label_29.setText(_fromUtf8(""))
        self.label_29.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/repko.png")))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_25.addWidget(self.label_29)
        self.verticalLayout_8.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.icon5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon5.sizePolicy().hasHeightForWidth())
        self.icon5.setSizePolicy(sizePolicy)
        self.icon5.setMaximumSize(QtCore.QSize(25, 16777215))
        self.icon5.setText(_fromUtf8(""))
        self.icon5.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/repko.png")))
        self.icon5.setObjectName(_fromUtf8("icon5"))
        self.horizontalLayout_21.addWidget(self.icon5)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/repko.png")))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_21.addWidget(self.label_21)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.icon6 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon6.sizePolicy().hasHeightForWidth())
        self.icon6.setSizePolicy(sizePolicy)
        self.icon6.setMaximumSize(QtCore.QSize(25, 16777215))
        self.icon6.setText(_fromUtf8(""))
        self.icon6.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/nonVide.png")))
        self.icon6.setObjectName(_fromUtf8("icon6"))
        self.horizontalLayout_18.addWidget(self.icon6)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/repko.png")))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_18.addWidget(self.label_11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.icon7 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon7.sizePolicy().hasHeightForWidth())
        self.icon7.setSizePolicy(sizePolicy)
        self.icon7.setMaximumSize(QtCore.QSize(25, 16777215))
        self.icon7.setText(_fromUtf8(""))
        self.icon7.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/rep2.png")))
        self.icon7.setObjectName(_fromUtf8("icon7"))
        self.horizontalLayout_19.addWidget(self.icon7)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/repko.png")))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_19.addWidget(self.label_13)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.icon8 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon8.sizePolicy().hasHeightForWidth())
        self.icon8.setSizePolicy(sizePolicy)
        self.icon8.setMaximumSize(QtCore.QSize(25, 16777215))
        self.icon8.setText(_fromUtf8(""))
        self.icon8.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/icon/repNormal1.png")))
        self.icon8.setObjectName(_fromUtf8("icon8"))
        self.horizontalLayout_20.addWidget(self.icon8)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setPixmap(QtWidgets.QPixmap(_fromUtf8("../../../../../../../../.designer/backup/repko.png")))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_20.addWidget(self.label_15)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.cbox_selections = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_selections.sizePolicy().hasHeightForWidth())
        self.cbox_selections.setSizePolicy(sizePolicy)
        self.cbox_selections.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_selections.setObjectName(_fromUtf8("cbox_selections"))
        self.horizontalLayout_3.addWidget(self.cbox_selections)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_13.addWidget(self.label_9)
        self.cbox_source = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_source.sizePolicy().hasHeightForWidth())
        self.cbox_source.setSizePolicy(sizePolicy)
        self.cbox_source.setMinimumSize(QtCore.QSize(150, 0))
        self.cbox_source.setObjectName(_fromUtf8("cbox_source"))
        self.cbox_source.addItem(_fromUtf8(""))
        self.cbox_source.addItem(_fromUtf8(""))
        self.cbox_source.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.cbox_source)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.cb_toutes = QtWidgets.QCheckBox(self.tab)
        self.cb_toutes.setChecked(True)
        self.cb_toutes.setObjectName(_fromUtf8("cb_toutes"))
        self.verticalLayout_5.addWidget(self.cb_toutes)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.cbAffTrierParDate = QtWidgets.QCheckBox(self.tab)
        self.cbAffTrierParDate.setChecked(True)
        self.cbAffTrierParDate.setObjectName(_fromUtf8("cbAffTrierParDate"))
        self.horizontalLayout_14.addWidget(self.cbAffTrierParDate)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_14.addWidget(self.label_12)
        self.edtFiltreNomAffichage = QtWidgets.QLineEdit(self.tab)
        self.edtFiltreNomAffichage.setObjectName(_fromUtf8("edtFiltreNomAffichage"))
        self.horizontalLayout_14.addWidget(self.edtFiltreNomAffichage)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.gb_infos = QtWidgets.QGroupBox(self.tab)
        self.gb_infos.setCheckable(True)
        self.gb_infos.setChecked(False)
        self.gb_infos.setObjectName(_fromUtf8("gb_infos"))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gb_infos)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cb_0_etoile = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_0_etoile.setChecked(True)
        self.cb_0_etoile.setObjectName(_fromUtf8("cb_0_etoile"))
        self.horizontalLayout.addWidget(self.cb_0_etoile)
        self.cb_1_etoile = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_1_etoile.setChecked(True)
        self.cb_1_etoile.setObjectName(_fromUtf8("cb_1_etoile"))
        self.horizontalLayout.addWidget(self.cb_1_etoile)
        self.cb_2_etoiles = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_2_etoiles.setChecked(True)
        self.cb_2_etoiles.setObjectName(_fromUtf8("cb_2_etoiles"))
        self.horizontalLayout.addWidget(self.cb_2_etoiles)
        self.cb_3_etoiles = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_3_etoiles.setChecked(True)
        self.cb_3_etoiles.setObjectName(_fromUtf8("cb_3_etoiles"))
        self.horizontalLayout.addWidget(self.cb_3_etoiles)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.cb_traitee = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_traitee.setTristate(True)
        self.cb_traitee.setObjectName(_fromUtf8("cb_traitee"))
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cb_traitee)
        self.cb_autre = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_autre.setTristate(True)
        self.cb_autre.setObjectName(_fromUtf8("cb_autre"))
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_autre)
        self.cb_panorama = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_panorama.setTristate(True)
        self.cb_panorama.setObjectName(_fromUtf8("cb_panorama"))
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cb_panorama)
        self.cb_paysage = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_paysage.setTristate(True)
        self.cb_paysage.setObjectName(_fromUtf8("cb_paysage"))
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_paysage)
        self.cb_retouche = QtWidgets.QCheckBox(self.gb_infos)
        self.cb_retouche.setChecked(False)
        self.cb_retouche.setTristate(True)
        self.cb_retouche.setObjectName(_fromUtf8("cb_retouche"))
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cb_retouche)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.verticalLayout_5.addWidget(self.gb_infos)
        self.gb_nums = QtWidgets.QGroupBox(self.tab)
        self.gb_nums.setCheckable(True)
        self.gb_nums.setChecked(False)
        self.gb_nums.setObjectName(_fromUtf8("gb_nums"))
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.gb_nums)
        self.verticalLayout_9.setContentsMargins(5,5,5,5)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtWidgets.QLabel(self.gb_nums)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.sb_min = QtWidgets.QSpinBox(self.gb_nums)
        self.sb_min.setMinimum(1)
        self.sb_min.setMaximum(9999)
        self.sb_min.setObjectName(_fromUtf8("sb_min"))
        self.horizontalLayout_4.addWidget(self.sb_min)
        self.label_2 = QtWidgets.QLabel(self.gb_nums)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.sb_max = QtWidgets.QSpinBox(self.gb_nums)
        self.sb_max.setMaximum(9999)
        self.sb_max.setObjectName(_fromUtf8("sb_max"))
        self.horizontalLayout_4.addWidget(self.sb_max)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addWidget(self.gb_nums)
        self.gb_dates = QtWidgets.QGroupBox(self.tab)
        self.gb_dates.setCheckable(True)
        self.gb_dates.setChecked(False)
        self.gb_dates.setObjectName(_fromUtf8("gb_dates"))
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.gb_dates)
        self.horizontalLayout_8.setContentsMargins(5,5,5,5)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.liste_dates = QtWidgets.QListWidget(self.gb_dates)
        self.liste_dates.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.liste_dates.setObjectName(_fromUtf8("liste_dates"))
        self.horizontalLayout_8.addWidget(self.liste_dates)
        self.verticalLayout_5.addWidget(self.gb_dates)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_10.addWidget(self.tableWidget)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_10.addWidget(self.label_5)
        self.edtAvant = QtWidgets.QLineEdit(self.tab_2)
        self.edtAvant.setObjectName(_fromUtf8("edtAvant"))
        self.horizontalLayout_10.addWidget(self.edtAvant)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_11.addWidget(self.label_6)
        self.edtApres = QtWidgets.QLineEdit(self.tab_2)
        self.edtApres.setObjectName(_fromUtf8("edtApres"))
        self.horizontalLayout_11.addWidget(self.edtApres)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.cbRenTrierParDate = QtWidgets.QCheckBox(self.tab_2)
        self.cbRenTrierParDate.setChecked(True)
        self.cbRenTrierParDate.setObjectName(_fromUtf8("cbRenTrierParDate"))
        self.horizontalLayout_9.addWidget(self.cbRenTrierParDate)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(50, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_4.addWidget(self.label_7)
        self.sbValeurInit = QtWidgets.QSpinBox(self.tab_2)
        self.sbValeurInit.setMinimumSize(QtCore.QSize(50, 0))
        self.sbValeurInit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sbValeurInit.setMaximum(10000)
        self.sbValeurInit.setProperty("value", 1)
        self.sbValeurInit.setObjectName(_fromUtf8("sbValeurInit"))
        self.verticalLayout_4.addWidget(self.sbValeurInit)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(50, 0))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_11.addWidget(self.label_8)
        self.sbNbChiffres = QtWidgets.QSpinBox(self.tab_2)
        self.sbNbChiffres.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sbNbChiffres.setMaximum(9)
        self.sbNbChiffres.setProperty("value", 3)
        self.sbNbChiffres.setObjectName(_fromUtf8("sbNbChiffres"))
        self.verticalLayout_11.addWidget(self.sbNbChiffres)
        self.horizontalLayout_9.addLayout(self.verticalLayout_11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.btDetruire = QtWidgets.QPushButton(self.tab_2)
        self.btDetruire.setMaximumSize(QtCore.QSize(70, 16777215))
        self.btDetruire.setObjectName(_fromUtf8("btDetruire"))
        self.horizontalLayout_12.addWidget(self.btDetruire)
        self.btAuto = QtWidgets.QPushButton(self.tab_2)
        self.btAuto.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btAuto.setObjectName(_fromUtf8("btAuto"))
        self.horizontalLayout_12.addWidget(self.btAuto)
        self.btAide = QtWidgets.QPushButton(self.tab_2)
        self.btAide.setText(_fromUtf8(""))
        self.btAide.setObjectName(_fromUtf8("btAide"))
        self.horizontalLayout_12.addWidget(self.btAide)
        self.btRefresh = QtWidgets.QPushButton(self.tab_2)
        self.btRefresh.setText(_fromUtf8(""))
        self.btRefresh.setObjectName(_fromUtf8("btRefresh"))
        self.horizontalLayout_12.addWidget(self.btRefresh)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.btTester = QtWidgets.QPushButton(self.tab_2)
        self.btTester.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btTester.setObjectName(_fromUtf8("btTester"))
        self.horizontalLayout_12.addWidget(self.btTester)
        self.btValider = QtWidgets.QPushButton(self.tab_2)
        self.btValider.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btValider.setObjectName(_fromUtf8("btValider"))
        self.horizontalLayout_12.addWidget(self.btValider)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidgetCompression = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidgetCompression.setObjectName(_fromUtf8("tableWidgetCompression"))
        self.tableWidgetCompression.setColumnCount(3)
        self.tableWidgetCompression.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCompression.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCompression.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCompression.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.tableWidgetCompression)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_27.addWidget(self.label_17)
        self.repertoire = QtWidgets.QLineEdit(self.tab_4)
        self.repertoire.setObjectName(_fromUtf8("repertoire"))
        self.horizontalLayout_27.addWidget(self.repertoire)
        self.bt_repertoire = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_repertoire.sizePolicy().hasHeightForWidth())
        self.bt_repertoire.setSizePolicy(sizePolicy)
        self.bt_repertoire.setMinimumSize(QtCore.QSize(40, 0))
        self.bt_repertoire.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bt_repertoire.setObjectName(_fromUtf8("bt_repertoire"))
        self.horizontalLayout_27.addWidget(self.bt_repertoire)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_29.addWidget(self.label_20)
        self.edtPrefixe = QtWidgets.QLineEdit(self.tab_4)
        self.edtPrefixe.setObjectName(_fromUtf8("edtPrefixe"))
        self.horizontalLayout_29.addWidget(self.edtPrefixe)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.bt_copie = QtWidgets.QRadioButton(self.tab_4)
        self.bt_copie.setObjectName(_fromUtf8("bt_copie"))
        self.verticalLayout_12.addWidget(self.bt_copie)
        self.bt_compression = QtWidgets.QRadioButton(self.tab_4)
        self.bt_compression.setObjectName(_fromUtf8("bt_compression"))
        self.verticalLayout_12.addWidget(self.bt_compression)
        self.reduction = QtWidgets.QHBoxLayout()
        self.reduction.setObjectName(_fromUtf8("reduction"))
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.reduction.addWidget(self.label_18)
        self.sb_reduction = QtWidgets.QSpinBox(self.tab_4)
        self.sb_reduction.setMinimum(1)
        self.sb_reduction.setMaximum(10)
        self.sb_reduction.setProperty("value", 2)
        self.sb_reduction.setObjectName(_fromUtf8("sb_reduction"))
        self.reduction.addWidget(self.sb_reduction)
        self.verticalLayout_12.addLayout(self.reduction)
        self.qualite = QtWidgets.QHBoxLayout()
        self.qualite.setObjectName(_fromUtf8("qualite"))
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.qualite.addWidget(self.label_19)
        self.sb_qualite = QtWidgets.QSpinBox(self.tab_4)
        self.sb_qualite.setMaximum(100)
        self.sb_qualite.setProperty("value", 90)
        self.sb_qualite.setObjectName(_fromUtf8("sb_qualite"))
        self.qualite.addWidget(self.sb_qualite)
        self.verticalLayout_12.addLayout(self.qualite)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.widget = QtWidgets.QWidget(self.tab_4)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_28.setMargin(0)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_22 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_30.addWidget(self.label_22)
        self.edtFiltre = QtWidgets.QLineEdit(self.widget)
        self.edtFiltre.setObjectName(_fromUtf8("edtFiltre"))
        self.horizontalLayout_30.addWidget(self.edtFiltre)
        self.verticalLayout_13.addLayout(self.horizontalLayout_30)
        self.rb_toutes = QtWidgets.QRadioButton(self.widget)
        self.rb_toutes.setChecked(True)
        self.rb_toutes.setObjectName(_fromUtf8("rb_toutes"))
        self.verticalLayout_13.addWidget(self.rb_toutes)
        self.rb_affichees = QtWidgets.QRadioButton(self.widget)
        self.rb_affichees.setObjectName(_fromUtf8("rb_affichees"))
        self.verticalLayout_13.addWidget(self.rb_affichees)
        self.rb_selection = QtWidgets.QRadioButton(self.widget)
        self.rb_selection.setObjectName(_fromUtf8("rb_selection"))
        self.verticalLayout_13.addWidget(self.rb_selection)
        self.horizontalLayout_28.addLayout(self.verticalLayout_13)
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.btAfficherCompression = QtWidgets.QPushButton(self.tab_4)
        self.btAfficherCompression.setObjectName(_fromUtf8("btAfficherCompression"))
        self.verticalLayout_14.addWidget(self.btAfficherCompression)
        self.btValiderCompression = QtWidgets.QPushButton(self.tab_4)
        self.btValiderCompression.setObjectName(_fromUtf8("btValiderCompression"))
        self.verticalLayout_14.addWidget(self.btValiderCompression)
        self.horizontalLayout_2.addLayout(self.verticalLayout_14)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.splitter)
        Arborescence.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Arborescence)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        Arborescence.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Arborescence)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Arborescence.setStatusBar(self.statusbar)
        self.actionRecreerMiniatures = QtWidgets.QAction(Arborescence)
        self.actionRecreerMiniatures.setObjectName(_fromUtf8("actionRecreerMiniatures"))
        self.actionMajMiniatures = QtWidgets.QAction(Arborescence)
        self.actionMajMiniatures.setObjectName(_fromUtf8("actionMajMiniatures"))
        self.actionDeplacerPhotos = QtWidgets.QAction(Arborescence)
        self.actionDeplacerPhotos.setObjectName(_fromUtf8("actionDeplacerPhotos"))
        self.actionDetruireTriPhotos = QtWidgets.QAction(Arborescence)
        self.actionDetruireTriPhotos.setObjectName(_fromUtf8("actionDetruireTriPhotos"))
        self.actionReinitialiser = QtWidgets.QAction(Arborescence)
        self.actionReinitialiser.setObjectName(_fromUtf8("actionReinitialiser"))
        self.actionQuitter = QtWidgets.QAction(Arborescence)
        self.actionQuitter.setObjectName(_fromUtf8("actionQuitter"))
        self.actionRenommer_fichiers = QtWidgets.QAction(Arborescence)
        self.actionRenommer_fichiers.setObjectName(_fromUtf8("actionRenommer_fichiers"))
        self.actionTelecharger = QtWidgets.QAction(Arborescence)
        self.actionTelecharger.setObjectName(_fromUtf8("actionTelecharger"))
        self.menuFile.addAction(self.actionQuitter)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Arborescence)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Arborescence)

    def retranslateUi(self, Arborescence):
        Arborescence.setWindowTitle(_translate("Arborescence", "Arborescence", None))
        self.label_3.setText(_translate("Arborescence", "Répertoire", None))
        self.btAddWorkspace.setText(_translate("Arborescence", "...", None))
        self.bt_annuler_progress.setText(_translate("Arborescence", "Stop", None))
        self.btAfficher.setText(_translate("Arborescence", "Afficher", None))
        self.btDeplacerImages.setText(_translate("Arborescence", "Déplacer images sélectionnées\n"
" dans l\'album", None))
        self.btCopierImages.setText(_translate("Arborescence", "Copier images sélectionnées\n"
" dans l\'album", None))
        self.photo.setText(_translate("Arborescence", "TextLabel", None))
        self.groupBox.setTitle(_translate("Arborescence", "Répertoires", None))
        self.label_10.setText(_translate("Arborescence", "Répertoire à déplacer", None))
        self.btSupprimerRepertoire.setText(_translate("Arborescence", "Supprimer ..", None))
        self.btDeplacerRepertoire.setText(_translate("Arborescence", "Déplacer ..", None))
        self.btCtrlXRepertoire.setText(_translate("Arborescence", "Ctrl X", None))
        self.btCreerRepertoire.setText(_translate("Arborescence", "Créer ..", None))
        self.btViderRepertoire.setText(_translate("Arborescence", "Vider", None))
        self.groupBox_2.setTitle(_translate("Arborescence", "Album", None))
        self.btRecreerMiniatures.setText(_translate("Arborescence", "Recréer Miniatures", None))
        self.btDetruireTriPhotos.setText(_translate("Arborescence", "Détruire TriPhotos", None))
        self.cb_album_termine.setText(_translate("Arborescence", "Album terminé", None))
        self.nb_pano.setText(_translate("Arborescence", "99990", None))
        self.label_26.setText(_translate("Arborescence", "Pano /", None))
        self.nb_recup.setText(_translate("Arborescence", "99990", None))
        self.label_27.setText(_translate("Arborescence", "Récupèration /", None))
        self.nb_retouche.setText(_translate("Arborescence", "99990", None))
        self.label_28.setText(_translate("Arborescence", "Retouche", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Arborescence", "Gestion album", None))
        self.label_4.setText(_translate("Arborescence", "Selection", None))
        self.label_9.setText(_translate("Arborescence", "Source   ", None))
        self.cbox_source.setItemText(0, _translate("Arborescence", "Photo", None))
        self.cbox_source.setItemText(1, _translate("Arborescence", "Panorama", None))
        self.cbox_source.setItemText(2, _translate("Arborescence", "Retouche", None))
        self.cb_toutes.setText(_translate("Arborescence", "Toutes", None))
        self.cbAffTrierParDate.setText(_translate("Arborescence", "Trier par date", None))
        self.label_12.setText(_translate("Arborescence", "Nom", None))
        self.gb_infos.setTitle(_translate("Arborescence", "Infos", None))
        self.cb_0_etoile.setText(_translate("Arborescence", "0", None))
        self.cb_1_etoile.setText(_translate("Arborescence", "1", None))
        self.cb_2_etoiles.setText(_translate("Arborescence", "2", None))
        self.cb_3_etoiles.setText(_translate("Arborescence", "3", None))
        self.cb_traitee.setText(_translate("Arborescence", "Traitée", None))
        self.cb_autre.setText(_translate("Arborescence", "Autre", None))
        self.cb_panorama.setText(_translate("Arborescence", "Panorama", None))
        self.cb_paysage.setText(_translate("Arborescence", "Paysage", None))
        self.cb_retouche.setText(_translate("Arborescence", "Retouche", None))
        self.gb_nums.setTitle(_translate("Arborescence", "Numéros photos", None))
        self.label.setText(_translate("Arborescence", "Photo", None))
        self.label_2.setText(_translate("Arborescence", "jusqu\'a", None))
        self.gb_dates.setTitle(_translate("Arborescence", "Date de prise de vue", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Arborescence", "Affichage", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Arborescence", "Actuel", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Arborescence", "Nouveau", None))
        self.label_5.setText(_translate("Arborescence", "Avant", None))
        self.label_6.setText(_translate("Arborescence", "Après", None))
        self.cbRenTrierParDate.setText(_translate("Arborescence", "Trier par date", None))
        self.label_7.setText(_translate("Arborescence", "Valeur init", None))
        self.label_8.setText(_translate("Arborescence", "Nb chiffres", None))
        self.btDetruire.setToolTip(_translate("Arborescence", "Détruit les images dont le filtre match", None))
        self.btDetruire.setText(_translate("Arborescence", "Détruire ...", None))
        self.btAuto.setText(_translate("Arborescence", "Auto", None))
        self.btTester.setText(_translate("Arborescence", "Tester", None))
        self.btValider.setText(_translate("Arborescence", "Valider", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Arborescence", "Renommage", None))
        item = self.tableWidgetCompression.horizontalHeaderItem(0)
        item.setText(_translate("Arborescence", "Nom", None))
        item = self.tableWidgetCompression.horizontalHeaderItem(1)
        item.setText(_translate("Arborescence", "Actuelle", None))
        item = self.tableWidgetCompression.horizontalHeaderItem(2)
        item.setText(_translate("Arborescence", "Estimée", None))
        self.label_17.setText(_translate("Arborescence", "Destination", None))
        self.bt_repertoire.setText(_translate("Arborescence", "...", None))
        self.label_20.setText(_translate("Arborescence", "prefixe", None))
        self.bt_copie.setText(_translate("Arborescence", "Copie", None))
        self.bt_compression.setText(_translate("Arborescence", "Compression", None))
        self.label_18.setText(_translate("Arborescence", "Reduction", None))
        self.label_19.setText(_translate("Arborescence", "Qualité", None))
        self.label_22.setText(_translate("Arborescence", "filtre", None))
        self.rb_toutes.setText(_translate("Arborescence", "Toutes", None))
        self.rb_affichees.setText(_translate("Arborescence", "filtre affichage", None))
        self.rb_selection.setText(_translate("Arborescence", "selection", None))
        self.btAfficherCompression.setText(_translate("Arborescence", "Afficher", None))
        self.btValiderCompression.setText(_translate("Arborescence", "Valider", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Arborescence", "Compression", None))
        self.menuFile.setTitle(_translate("Arborescence", "Fichier", None))
        self.actionRecreerMiniatures.setText(_translate("Arborescence", "Recréer miniatures", None))
        self.actionRecreerMiniatures.setToolTip(_translate("Arborescence", "Détruit les miniatures et les recrée", None))
        self.actionMajMiniatures.setText(_translate("Arborescence", "Mise à jour miniatures", None))
        self.actionDeplacerPhotos.setText(_translate("Arborescence", "Déplacer photos", None))
        self.actionDetruireTriPhotos.setText(_translate("Arborescence", "Détruire TriPhotos", None))
        self.actionDetruireTriPhotos.setToolTip(_translate("Arborescence", "Détruit toute l\'arborescence TriPhotos", None))
        self.actionReinitialiser.setText(_translate("Arborescence", "Réinitialiser", None))
        self.actionQuitter.setText(_translate("Arborescence", "Quitter", None))
        self.actionRenommer_fichiers.setText(_translate("Arborescence", "Renommer fichiers", None))
        self.actionTelecharger.setText(_translate("Arborescence", "Télécharger", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Arborescence = QtWidgets.QMainWindow()
    ui = Ui_Arborescence()
    ui.setupUi(Arborescence)
    Arborescence.show()
    sys.exit(app.exec_())

