# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Ihm\fen_etoiles.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Etoiles(object):
    def setupUi(self, Etoiles):
        Etoiles.setObjectName(_fromUtf8("Etoiles"))
        Etoiles.resize(70, 42)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Etoiles)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtWidgets.QLabel(Etoiles)
        palette = QtWidgets.QPalette()
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.WindowText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Button, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Light, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Midlight, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Dark, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Mid, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Text, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.BrightText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.ButtonText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Base, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Window, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Shadow, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.AlternateBase, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.ToolTipBase, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.ToolTipText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.WindowText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Button, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Light, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Midlight, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Dark, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Mid, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Text, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.BrightText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.ButtonText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Base, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Window, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Shadow, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.AlternateBase, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.ToolTipBase, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.ToolTipText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.WindowText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Button, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Light, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Midlight, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Dark, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Mid, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Text, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.BrightText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.ButtonText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Base, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Window, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Shadow, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.AlternateBase, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.ToolTipBase, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.ToolTipText, brush)
        self.label.setPalette(palette)
        font = QtWidgets.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)

        self.retranslateUi(Etoiles)
        QtCore.QMetaObject.connectSlotsByName(Etoiles)

    def retranslateUi(self, Etoiles):
        Etoiles.setWindowTitle(_translate("Etoiles", "Form", None))
        self.label.setText(_translate("Etoiles", "3", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Etoiles = QtWidgets.QWidget()
    ui = Ui_Etoiles()
    ui.setupUi(Etoiles)
    Etoiles.show()
    sys.exit(app.exec_())

