# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Ihm\fen_miniatures.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Miniatures(object):
    def setupUi(self, Miniatures):
        Miniatures.setObjectName(_fromUtf8("Miniatures"))
        Miniatures.resize(421, 299)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Miniatures.sizePolicy().hasHeightForWidth())
        Miniatures.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Miniatures)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollWidget = QtWidgets.QWidget()
        self.scrollWidget.setGeometry(QtCore.QRect(0, 0, 419, 263))
        self.scrollWidget.setObjectName(_fromUtf8("scrollWidget"))
        self.gridLayout = QtWidgets.QGridLayout(self.scrollWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.images = QtWidgets.QGridLayout()
        self.images.setSpacing(0)
        self.images.setObjectName(_fromUtf8("images"))
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.images.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.images, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollWidget)
        self.verticalLayout.addWidget(self.scrollArea)
        self.commentaire = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentaire.sizePolicy().hasHeightForWidth())
        self.commentaire.setSizePolicy(sizePolicy)
        self.commentaire.setText(_fromUtf8(""))
        self.commentaire.setObjectName(_fromUtf8("commentaire"))
        self.verticalLayout.addWidget(self.commentaire)
        Miniatures.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Miniatures)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuInfos = QtWidgets.QMenu(self.menubar)
        self.menuInfos.setObjectName(_fromUtf8("menuInfos"))
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menuPhoto = QtWidgets.QMenu(self.menubar)
        self.menuPhoto.setObjectName(_fromUtf8("menuPhoto"))
        self.menuSelection_2 = QtWidgets.QMenu(self.menubar)
        self.menuSelection_2.setObjectName(_fromUtf8("menuSelection_2"))
        self.menuPanorama = QtWidgets.QMenu(self.menubar)
        self.menuPanorama.setObjectName(_fromUtf8("menuPanorama"))
        Miniatures.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Miniatures)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Miniatures.setStatusBar(self.statusbar)
        self.actionChoisir_repertoire = QtWidgets.QAction(Miniatures)
        self.actionChoisir_repertoire.setObjectName(_fromUtf8("actionChoisir_repertoire"))
        self.actionQuitter = QtWidgets.QAction(Miniatures)
        self.actionQuitter.setObjectName(_fromUtf8("actionQuitter"))
        self.actionChargerSelection = QtWidgets.QAction(Miniatures)
        self.actionChargerSelection.setObjectName(_fromUtf8("actionChargerSelection"))
        self.actionSauverSelection = QtWidgets.QAction(Miniatures)
        self.actionSauverSelection.setObjectName(_fromUtf8("actionSauverSelection"))
        self.actionModifierFiltre = QtWidgets.QAction(Miniatures)
        self.actionModifierFiltre.setObjectName(_fromUtf8("actionModifierFiltre"))
        self.actionPreferences = QtWidgets.QAction(Miniatures)
        self.actionPreferences.setEnabled(False)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionModifierInfos = QtWidgets.QAction(Miniatures)
        self.actionModifierInfos.setObjectName(_fromUtf8("actionModifierInfos"))
        self.actionGenererSelection = QtWidgets.QAction(Miniatures)
        self.actionGenererSelection.setObjectName(_fromUtf8("actionGenererSelection"))
        self.actionDiaporama = QtWidgets.QAction(Miniatures)
        self.actionDiaporama.setObjectName(_fromUtf8("actionDiaporama"))
        self.actionDeplacer_panorama = QtWidgets.QAction(Miniatures)
        self.actionDeplacer_panorama.setObjectName(_fromUtf8("actionDeplacer_panorama"))
        self.actionCopier_retouche = QtWidgets.QAction(Miniatures)
        self.actionCopier_retouche.setObjectName(_fromUtf8("actionCopier_retouche"))
        self.actionDetectionAutomatique = QtWidgets.QAction(Miniatures)
        self.actionDetectionAutomatique.setObjectName(_fromUtf8("actionDetectionAutomatique"))
        self.actionAide = QtWidgets.QAction(Miniatures)
        self.actionAide.setObjectName(_fromUtf8("actionAide"))
        self.actionDetruire = QtWidgets.QAction(Miniatures)
        self.actionDetruire.setObjectName(_fromUtf8("actionDetruire"))
        self.actionRenommer = QtWidgets.QAction(Miniatures)
        self.actionRenommer.setObjectName(_fromUtf8("actionRenommer"))
        self.actionTrierParDate = QtWidgets.QAction(Miniatures)
        self.actionTrierParDate.setObjectName(_fromUtf8("actionTrierParDate"))
        self.actionSauverSelectionSous = QtWidgets.QAction(Miniatures)
        self.actionSauverSelectionSous.setObjectName(_fromUtf8("actionSauverSelectionSous"))
        self.actionNouvelleSelection = QtWidgets.QAction(Miniatures)
        self.actionNouvelleSelection.setObjectName(_fromUtf8("actionNouvelleSelection"))
        self.actionDetruireSelection = QtWidgets.QAction(Miniatures)
        self.actionDetruireSelection.setObjectName(_fromUtf8("actionDetruireSelection"))
        self.actionDeplacer = QtWidgets.QAction(Miniatures)
        self.actionDeplacer.setObjectName(_fromUtf8("actionDeplacer"))
        self.actionSauverInfos = QtWidgets.QAction(Miniatures)
        self.actionSauverInfos.setObjectName(_fromUtf8("actionSauverInfos"))
        self.actionRenommer_panorama = QtWidgets.QAction(Miniatures)
        self.actionRenommer_panorama.setObjectName(_fromUtf8("actionRenommer_panorama"))
        self.actionRenommage_auto = QtWidgets.QAction(Miniatures)
        self.actionRenommage_auto.setObjectName(_fromUtf8("actionRenommage_auto"))
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuitter)
        self.menuInfos.addAction(self.actionModifierInfos)
        self.menuInfos.addAction(self.actionSauverInfos)
        self.menuInfos.addSeparator()
        self.menu.addAction(self.actionAide)
        self.menuPhoto.addAction(self.actionDetruire)
        self.menuPhoto.addAction(self.actionRenommage_auto)
        self.menuPhoto.addSeparator()
        self.menuPhoto.addAction(self.actionCopier_retouche)
        self.menuSelection_2.addAction(self.actionNouvelleSelection)
        self.menuSelection_2.addAction(self.actionSauverSelection)
        self.menuSelection_2.addSeparator()
        self.menuSelection_2.addAction(self.actionChargerSelection)
        self.menuSelection_2.addAction(self.actionSauverSelectionSous)
        self.menuSelection_2.addAction(self.actionDetruireSelection)
        self.menuSelection_2.addSeparator()
        self.menuSelection_2.addAction(self.actionGenererSelection)
        self.menuPanorama.addAction(self.actionRenommer_panorama)
        self.menuPanorama.addAction(self.actionDeplacer_panorama)
        self.menuPanorama.addAction(self.actionDetectionAutomatique)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSelection_2.menuAction())
        self.menubar.addAction(self.menuInfos.menuAction())
        self.menubar.addAction(self.menuPhoto.menuAction())
        self.menubar.addAction(self.menuPanorama.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Miniatures)
        QtCore.QObject.connect(Miniatures, QtCore.SIGNAL(_fromUtf8("destroyed()")), Miniatures.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(Miniatures)

    def retranslateUi(self, Miniatures):
        Miniatures.setWindowTitle(_translate("Miniatures", "Tri Photos", None))
        self.menuFile.setTitle(_translate("Miniatures", "Fichier", None))
        self.menuInfos.setTitle(_translate("Miniatures", "Infos", None))
        self.menu.setTitle(_translate("Miniatures", "?", None))
        self.menuPhoto.setTitle(_translate("Miniatures", "Photo", None))
        self.menuSelection_2.setTitle(_translate("Miniatures", "Selection", None))
        self.menuPanorama.setTitle(_translate("Miniatures", "Panorama", None))
        self.actionChoisir_repertoire.setText(_translate("Miniatures", "Choisir repertoire / filtre ...", None))
        self.actionQuitter.setText(_translate("Miniatures", "Quitter", None))
        self.actionChargerSelection.setText(_translate("Miniatures", "Charger ...", None))
        self.actionSauverSelection.setText(_translate("Miniatures", "Sauver", None))
        self.actionModifierFiltre.setText(_translate("Miniatures", "Modifier ...", None))
        self.actionPreferences.setText(_translate("Miniatures", "Préférences ...", None))
        self.actionModifierInfos.setText(_translate("Miniatures", "Modifier ...", None))
        self.actionGenererSelection.setText(_translate("Miniatures", "Générer ...", None))
        self.actionDiaporama.setText(_translate("Miniatures", "Diaporama ...", None))
        self.actionDeplacer_panorama.setText(_translate("Miniatures", "Deplacer panorama", None))
        self.actionCopier_retouche.setText(_translate("Miniatures", "Copier retouche", None))
        self.actionDetectionAutomatique.setText(_translate("Miniatures", "Détection automatique", None))
        self.actionAide.setText(_translate("Miniatures", "Aide", None))
        self.actionDetruire.setText(_translate("Miniatures", "Détruire les photos selectionnés ...", None))
        self.actionRenommer.setText(_translate("Miniatures", "Renommer ...", None))
        self.actionTrierParDate.setText(_translate("Miniatures", "Trier par date ", None))
        self.actionSauverSelectionSous.setText(_translate("Miniatures", "Sauver sous ...", None))
        self.actionNouvelleSelection.setText(_translate("Miniatures", "Nouvelle", None))
        self.actionDetruireSelection.setText(_translate("Miniatures", "Détruire ...", None))
        self.actionDeplacer.setText(_translate("Miniatures", "Déplacer", None))
        self.actionSauverInfos.setText(_translate("Miniatures", "Sauver", None))
        self.actionRenommer_panorama.setText(_translate("Miniatures", "Renommer panorama", None))
        self.actionRenommage_auto.setText(_translate("Miniatures", "Renommage automatique", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Miniatures = QtWidgets.QMainWindow()
    ui = Ui_Miniatures()
    ui.setupUi(Miniatures)
    Miniatures.show()
    sys.exit(app.exec_())

