# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ihm\fen_diaporama.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Diaporama(object):
    def setupUi(self, Diaporama):
        Diaporama.setObjectName("Diaporama")
        Diaporama.resize(428, 72)
        self.verticalLayout = QtWidgets.QVBoxLayout(Diaporama)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_quitter = QtWidgets.QPushButton(Diaporama)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_quitter.setFont(font)
        self.bt_quitter.setObjectName("bt_quitter")
        self.horizontalLayout.addWidget(self.bt_quitter)
        self.label_2 = QtWidgets.QLabel(Diaporama)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.sb_tempo = QtWidgets.QSpinBox(Diaporama)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_tempo.sizePolicy().hasHeightForWidth())
        self.sb_tempo.setSizePolicy(sizePolicy)
        self.sb_tempo.setMinimumSize(QtCore.QSize(60, 0))
        self.sb_tempo.setObjectName("sb_tempo")
        self.horizontalLayout.addWidget(self.sb_tempo)
        self.bt_go_stop = QtWidgets.QPushButton(Diaporama)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_go_stop.setFont(font)
        self.bt_go_stop.setObjectName("bt_go_stop")
        self.horizontalLayout.addWidget(self.bt_go_stop)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Diaporama)
        QtCore.QMetaObject.connectSlotsByName(Diaporama)

    def retranslateUi(self, Diaporama):
        _translate = QtCore.QCoreApplication.translate
        Diaporama.setWindowTitle(_translate("Diaporama", "Diaporama"))
        self.bt_quitter.setText(_translate("Diaporama", "Quitter"))
        self.label_2.setText(_translate("Diaporama", "Temporisation (sec)"))
        self.bt_go_stop.setText(_translate("Diaporama", "Lancer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Diaporama = QtWidgets.QDialog()
    ui = Ui_Diaporama()
    ui.setupUi(Diaporama)
    Diaporama.show()
    sys.exit(app.exec_())
