# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Ihm\fen_visionneuse.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Visionneuse(object):
    def setupUi(self, Visionneuse):
        Visionneuse.setObjectName(_fromUtf8("Visionneuse"))
        Visionneuse.resize(564, 543)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Visionneuse.sizePolicy().hasHeightForWidth())
        Visionneuse.setSizePolicy(sizePolicy)
        palette = QtWidgets.QPalette()
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Base, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Window, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Base, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Window, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Base, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Window, brush)
        Visionneuse.setPalette(palette)
        Visionneuse.setMouseTracking(True)
        Visionneuse.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label = QtWidgets.QLabel(Visionneuse)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 0, 49, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMouseTracking(True)
        self.label.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.lbl_etoiles = QtWidgets.QLabel(Visionneuse)
        self.lbl_etoiles.setGeometry(QtCore.QRect(0, 0, 52, 24))
        palette = QtWidgets.QPalette()
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.WindowText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Button, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Light, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Midlight, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Dark, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Mid, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Text, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.BrightText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.ButtonText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Base, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Window, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.Shadow, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.AlternateBase, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.ToolTipBase, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Active, QtWidgets.QPalette.ToolTipText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.WindowText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Button, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Light, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Midlight, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Dark, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Mid, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Text, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.BrightText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.ButtonText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Base, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Window, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.Shadow, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.AlternateBase, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.ToolTipBase, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Inactive, QtWidgets.QPalette.ToolTipText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.WindowText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Button, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Light, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Midlight, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Dark, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Mid, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Text, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.BrightText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.ButtonText, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Base, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Window, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.Shadow, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.AlternateBase, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.ToolTipBase, brush)
        brush = QtWidgets.QBrush(QtWidgets.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtWidgets.QPalette.Disabled, QtWidgets.QPalette.ToolTipText, brush)
        self.lbl_etoiles.setPalette(palette)
        font = QtWidgets.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_etoiles.setFont(font)
        self.lbl_etoiles.setText(_fromUtf8(""))
        self.lbl_etoiles.setObjectName(_fromUtf8("lbl_etoiles"))

        self.retranslateUi(Visionneuse)
        QtCore.QMetaObject.connectSlotsByName(Visionneuse)

    def retranslateUi(self, Visionneuse):
        Visionneuse.setWindowTitle(_translate("Visionneuse", "Form", None))
        self.label.setText(_translate("Visionneuse", "TextLabel", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Visionneuse = QtWidgets.QWidget()
    ui = Ui_Visionneuse()
    ui.setupUi(Visionneuse)
    Visionneuse.show()
    sys.exit(app.exec_())

