# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ihm\fen_preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(322, 193)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Preferences)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox = QtWidgets.QGroupBox(Preferences)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 117, 44))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_thumbs = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_thumbs.setChecked(True)
        self.cb_thumbs.setObjectName("cb_thumbs")
        self.verticalLayout.addWidget(self.cb_thumbs)
        self.cb_photo = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_photo.setChecked(True)
        self.cb_photo.setObjectName("cb_photo")
        self.verticalLayout.addWidget(self.cb_photo)
        self.horizontalLayout_11.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.buttonBox = QtWidgets.QDialogButtonBox(Preferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Preferences)
        self.buttonBox.accepted.connect(Preferences.accept) # type: ignore
        self.buttonBox.rejected.connect(Preferences.reject) # type: ignore
        self.buttonBox.clicked['QAbstractButton*'].connect(Preferences.update) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        _translate = QtCore.QCoreApplication.translate
        Preferences.setWindowTitle(_translate("Preferences", "Préférences"))
        self.groupBox.setTitle(_translate("Preferences", "Plein écran"))
        self.cb_thumbs.setText(_translate("Preferences", "Fenêtre miniatures"))
        self.cb_photo.setText(_translate("Preferences", "fenêtre photo"))
