# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ihm\widget_miniature_vert.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MiniatureVer(object):
    def setupUi(self, MiniatureVer):
        MiniatureVer.setObjectName("MiniatureVer")
        MiniatureVer.resize(269, 190)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(MiniatureVer)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(MiniatureVer)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_1.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.nom_pano = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nom_pano.setFont(font)
        self.nom_pano.setText("")
        self.nom_pano.setObjectName("nom_pano")
        self.verticalLayout.addWidget(self.nom_pano)
        self.etoile = QtWidgets.QLabel(self.frame)
        self.etoile.setObjectName("etoile")
        self.verticalLayout.addWidget(self.etoile)
        self.traitee = QtWidgets.QCheckBox(self.frame)
        self.traitee.setObjectName("traitee")
        self.verticalLayout.addWidget(self.traitee)
        self.panorama = QtWidgets.QCheckBox(self.frame)
        self.panorama.setObjectName("panorama")
        self.verticalLayout.addWidget(self.panorama)
        self.retouche = QtWidgets.QCheckBox(self.frame)
        self.retouche.setObjectName("retouche")
        self.verticalLayout.addWidget(self.retouche)
        self.autre = QtWidgets.QCheckBox(self.frame)
        self.autre.setObjectName("autre")
        self.verticalLayout.addWidget(self.autre)
        self.verticalLayout_1.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_1)
        self.horizontalLayout_2.addWidget(self.frame)

        self.retranslateUi(MiniatureVer)
        QtCore.QMetaObject.connectSlotsByName(MiniatureVer)

    def retranslateUi(self, MiniatureVer):
        _translate = QtCore.QCoreApplication.translate
        MiniatureVer.setWindowTitle(_translate("MiniatureVer", "Form"))
        self.etoile.setText(_translate("MiniatureVer", "etoile"))
        self.traitee.setText(_translate("MiniatureVer", "traitée"))
        self.panorama.setText(_translate("MiniatureVer", "panorama"))
        self.retouche.setText(_translate("MiniatureVer", "retouche"))
        self.autre.setText(_translate("MiniatureVer", "autre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MiniatureVer = QtWidgets.QWidget()
    ui = Ui_MiniatureVer()
    ui.setupUi(MiniatureVer)
    MiniatureVer.show()
    sys.exit(app.exec_())
