# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ihm\widget_miniature.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Miniature(object):
    def setupUi(self, Miniature):
        Miniature.setObjectName("Miniature")
        Miniature.resize(337, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Miniature)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Miniature)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Miniature)
        QtCore.QMetaObject.connectSlotsByName(Miniature)

    def retranslateUi(self, Miniature):
        _translate = QtCore.QCoreApplication.translate
        Miniature.setWindowTitle(_translate("Miniature", "Form"))
        self.label.setText(_translate("Miniature", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Miniature = QtWidgets.QWidget()
    ui = Ui_Miniature()
    ui.setupUi(Miniature)
    Miniature.show()
    sys.exit(app.exec_())
