# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ihm\widget_miniature_hor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MiniatureHor(object):
    def setupUi(self, MiniatureHor):
        MiniatureHor.setObjectName("MiniatureHor")
        MiniatureHor.resize(285, 212)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(MiniatureHor)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(MiniatureHor)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cb1 = QtWidgets.QVBoxLayout()
        self.cb1.setObjectName("cb1")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cb1.addItem(spacerItem1)
        self.nom_pano = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nom_pano.setFont(font)
        self.nom_pano.setText("")
        self.nom_pano.setObjectName("nom_pano")
        self.cb1.addWidget(self.nom_pano)
        self.traitee = QtWidgets.QCheckBox(self.frame)
        self.traitee.setObjectName("traitee")
        self.cb1.addWidget(self.traitee)
        self.panorama = QtWidgets.QCheckBox(self.frame)
        self.panorama.setObjectName("panorama")
        self.cb1.addWidget(self.panorama)
        self.retouche = QtWidgets.QCheckBox(self.frame)
        self.retouche.setObjectName("retouche")
        self.cb1.addWidget(self.retouche)
        self.horizontalLayout.addLayout(self.cb1)
        self.cb2 = QtWidgets.QVBoxLayout()
        self.cb2.setSpacing(0)
        self.cb2.setObjectName("cb2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cb2.addItem(spacerItem2)
        self.etoile = QtWidgets.QLabel(self.frame)
        self.etoile.setObjectName("etoile")
        self.cb2.addWidget(self.etoile)
        self.autre = QtWidgets.QCheckBox(self.frame)
        self.autre.setObjectName("autre")
        self.cb2.addWidget(self.autre)
        self.horizontalLayout.addLayout(self.cb2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addWidget(self.frame)

        self.retranslateUi(MiniatureHor)
        QtCore.QMetaObject.connectSlotsByName(MiniatureHor)

    def retranslateUi(self, MiniatureHor):
        _translate = QtCore.QCoreApplication.translate
        MiniatureHor.setWindowTitle(_translate("MiniatureHor", "Form"))
        self.traitee.setText(_translate("MiniatureHor", "traitée"))
        self.panorama.setText(_translate("MiniatureHor", "panorama"))
        self.retouche.setText(_translate("MiniatureHor", "retouche"))
        self.etoile.setText(_translate("MiniatureHor", "etoile"))
        self.autre.setText(_translate("MiniatureHor", "autre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MiniatureHor = QtWidgets.QWidget()
    ui = Ui_MiniatureHor()
    ui.setupUi(MiniatureHor)
    MiniatureHor.show()
    sys.exit(app.exec_())
