# -*- coding:utf-8 -*-
"""
Created on 29 juin 2011

@author: Bureau
"""
Exif.Image.Make
Exif.Image.Model
Exif.Image.Orientation
Exif.Image.XResolution
Exif.Image.YResolution
Exif.Image.ResolutionUnit
Exif.Image.DateTime
Exif.Image.YCbCrPositioning
Exif.Image.ExifTag
Exif.Photo.ExposureTime
Exif.Photo.FNumber
Exif.Photo.ExposureProgram
Exif.Photo.ISOSpeedRatings
Exif.Photo.ExifVersion
Exif.Photo.DateTimeOriginal
Exif.Photo.DateTimeDigitized
Exif.Photo.ComponentsConfiguration
Exif.Photo.ShutterSpeedValue
Exif.Photo.ApertureValue
Exif.Photo.ExposureBiasValue
Exif.Photo.MeteringMode
Exif.Photo.Flash
Exif.Photo.FocalLength
Exif.Photo.MakerNote
Exif.MakerNote.Offset
Exif.MakerNote.ByteOrder
Exif.CanonCs.0x0000
Exif.CanonCs.Macro
Exif.CanonCs.Selftimer
Exif.CanonCs.Quality
Exif.CanonCs.FlashMode
Exif.CanonCs.DriveMode
Exif.CanonCs.0x0006
Exif.CanonCs.FocusMode
Exif.CanonCs.0x0008
Exif.CanonCs.0x0009
Exif.CanonCs.ImageSize
Exif.CanonCs.EasyMode
Exif.CanonCs.DigitalZoom
Exif.CanonCs.Contrast
Exif.CanonCs.Saturation
Exif.CanonCs.Sharpness
Exif.CanonCs.ISOSpeed
Exif.CanonCs.MeteringMode
Exif.CanonCs.FocusType
Exif.CanonCs.AFPoint
Exif.CanonCs.ExposureProgram
Exif.CanonCs.0x0015
Exif.CanonCs.LensType
Exif.CanonCs.Lens
Exif.CanonCs.MaxAperture
Exif.CanonCs.MinAperture
Exif.CanonCs.FlashActivity
Exif.CanonCs.FlashDetails
Exif.CanonCs.0x001e
Exif.CanonCs.0x001f
Exif.CanonCs.FocusContinuous
Exif.CanonCs.AESetting
Exif.CanonCs.ImageStabilization
Exif.CanonCs.DisplayAperture
Exif.CanonCs.ZoomSourceWidth
Exif.CanonCs.ZoomTargetWidth
Exif.CanonCs.0x0026
Exif.CanonCs.0x0027
Exif.CanonCs.PhotoEffect
Exif.CanonCs.0x0029
Exif.CanonCs.ColorTone
Exif.CanonCs.0x002b
Exif.CanonCs.0x002c
Exif.CanonCs.0x002d
Exif.Canon.FocalLength
Exif.Canon.0x0003
Exif.CanonSi.0x0000
Exif.CanonSi.0x0001
Exif.CanonSi.ISOSpeed
Exif.CanonSi.0x0003
Exif.CanonSi.TargetAperture
Exif.CanonSi.TargetShutterSpeed
Exif.CanonSi.0x0006
Exif.CanonSi.WhiteBalance
Exif.CanonSi.0x0008
Exif.CanonSi.Sequence
Exif.CanonSi.0x000a
Exif.CanonSi.0x000b
Exif.CanonSi.0x000c
Exif.CanonSi.0x000d
Exif.CanonSi.AFPointUsed
Exif.CanonSi.FlashBias
Exif.CanonSi.0x0010
Exif.CanonSi.0x0011
Exif.CanonSi.0x0012
Exif.CanonSi.SubjectDistance
Exif.CanonSi.0x0014
Exif.CanonSi.ApertureValue
Exif.CanonSi.ShutterSpeedValue
Exif.CanonSi.0x0017
Exif.CanonSi.0x0018
Exif.CanonSi.0x0019
Exif.CanonSi.0x001a
Exif.CanonSi.0x001b
Exif.CanonSi.0x001c
Exif.CanonSi.0x001d
Exif.CanonSi.0x001e
Exif.CanonSi.0x001f
Exif.CanonSi.0x0020
Exif.CanonSi.0x0021
Exif.Canon.ImageType
Exif.Canon.FirmwareVersion
Exif.Canon.OwnerName
Exif.Canon.SerialNumber
Exif.Canon.0x000d
Exif.CanonCf.0x0000
Exif.CanonCf.NoiseReduction
Exif.CanonCf.ShutterAeLock
Exif.CanonCf.MirrorLockup
Exif.CanonCf.ExposureLevelIncrements
Exif.CanonCf.AFAssist
Exif.CanonCf.FlashSyncSpeedAv
Exif.CanonCf.AEBSequence
Exif.CanonCf.ShutterCurtainSync
Exif.CanonCf.LensAFStopButton
Exif.CanonCf.FillFlashAutoReduction
Exif.CanonCf.MenuButtonReturn
Exif.Canon.ModelID
Exif.CanonPi.0x0000
Exif.CanonPi.0x0001
Exif.CanonPi.ImageWidth
Exif.CanonPi.ImageHeight
Exif.CanonPi.ImageWidthAsShot
Exif.CanonPi.ImageHeightAsShot
Exif.CanonPi.0x0006
Exif.CanonPi.0x0007
Exif.CanonPi.0x0008
Exif.CanonPi.0x0009
Exif.CanonPi.0x000a
Exif.CanonPi.0x000b
Exif.CanonPi.0x000c
Exif.CanonPi.0x000d
Exif.CanonPi.0x000e
Exif.CanonPi.0x000f
Exif.CanonPi.0x0010
Exif.CanonPi.0x0011
Exif.CanonPi.0x0012
Exif.CanonPi.0x0013
Exif.CanonPi.0x0014
Exif.CanonPi.0x0015
Exif.CanonPi.AFPointsUsed
Exif.CanonPi.0x0017
Exif.CanonPi.0x0018
Exif.CanonPi.0x0019
Exif.CanonPi.AFPointsUsed20D
Exif.CanonPi.0x001b
Exif.Canon.0x0013
Exif.Canon.0x0015
Exif.Canon.0x0019
Exif.Canon.0x0083
Exif.CanonFi.0x0000
Exif.CanonFi.FileNumber
Exif.CanonFi.BracketMode
Exif.CanonFi.BracketValue
Exif.CanonFi.BracketShotNumber
Exif.CanonFi.RawJpgQuality
Exif.CanonFi.RawJpgSize
Exif.CanonFi.NoiseReduction
Exif.CanonFi.WBBracketMode
Exif.CanonFi.0x000a
Exif.CanonFi.0x000b
Exif.CanonFi.WBBracketValueAB
Exif.CanonFi.WBBracketValueGM
Exif.CanonFi.FilterEffect
Exif.CanonFi.ToningEffect
Exif.CanonFi.0x0010
Exif.Canon.0x0095
Exif.Canon.0x0096
Exif.Canon.0x0097
Exif.Canon.0x0098
Exif.Canon.0x00a0
Exif.Canon.0x00aa
Exif.Canon.0x00b4
Exif.Canon.0x00d0
Exif.Canon.0x00e0
Exif.Canon.0x4001
Exif.Canon.0x4008
Exif.Canon.0x4009
Exif.Canon.0x4010
Exif.Canon.0x4011
Exif.Photo.UserComment
Exif.Photo.FlashpixVersion
Exif.Photo.ColorSpace
Exif.Photo.PixelXDimension
Exif.Photo.PixelYDimension
Exif.Photo.InteroperabilityTag
Exif.Iop.InteroperabilityIndex
Exif.Iop.InteroperabilityVersion
Exif.Photo.FocalPlaneXResolution
Exif.Photo.FocalPlaneYResolution
Exif.Photo.FocalPlaneResolutionUnit
Exif.Photo.CustomRendered
Exif.Photo.ExposureMode
Exif.Photo.WhiteBalance
Exif.Photo.SceneCaptureType
Exif.Thumbnail.Compression
Exif.Thumbnail.XResolution
Exif.Thumbnail.YResolution
Exif.Thumbnail.ResolutionUnit
Exif.Thumbnail.JPEGInterchangeFormat
Exif.Thumbnail.JPEGInterchangeFormatLength
